# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.28.0
import dataclasses
import datetime
from typing import Optional


@dataclasses.dataclass()
class Lead:
    id: int
    first_name: Optional[str]
    last_name: Optional[str]
    email: Optional[str]
    phone: Optional[str]
    stage: int
    created_at: Optional[datetime.datetime]
