// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-axios';
import type { HealthCheckHealthGetData, ListLeadsApiLeadsGetData, ListLeadsApiLeadsGetResponse, ListLeadsApiLeadsGetError, CreateLeadApiLeadsPostData, CreateLeadApiLeadsPostResponse, CreateLeadApiLeadsPostError, DeleteLeadApiLeadsLeadIdDeleteData, DeleteLeadApiLeadsLeadIdDeleteResponse, DeleteLeadApiLeadsLeadIdDeleteError, UpdateLeadApiLeadsLeadIdPatchData, UpdateLeadApiLeadsLeadIdPatchError } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health Check
 */
export const healthCheckHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckHealthGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
        url: '/health',
        ...options
    });
};

/**
 * List Leads
 */
export const listLeadsApiLeadsGet = <ThrowOnError extends boolean = false>(options?: Options<ListLeadsApiLeadsGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ListLeadsApiLeadsGetResponse, ListLeadsApiLeadsGetError, ThrowOnError>({
        url: '/api/leads/',
        ...options
    });
};

/**
 * Create Lead
 */
export const createLeadApiLeadsPost = <ThrowOnError extends boolean = false>(options: Options<CreateLeadApiLeadsPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateLeadApiLeadsPostResponse, CreateLeadApiLeadsPostError, ThrowOnError>({
        url: '/api/leads/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Delete Lead
 */
export const deleteLeadApiLeadsLeadIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteLeadApiLeadsLeadIdDeleteData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteLeadApiLeadsLeadIdDeleteResponse, DeleteLeadApiLeadsLeadIdDeleteError, ThrowOnError>({
        url: '/api/leads/{lead_id}',
        ...options
    });
};

/**
 * Update Lead
 */
export const updateLeadApiLeadsLeadIdPatch = <ThrowOnError extends boolean = false>(options: Options<UpdateLeadApiLeadsLeadIdPatchData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<unknown, UpdateLeadApiLeadsLeadIdPatchError, ThrowOnError>({
        url: '/api/leads/{lead_id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};