// This file is auto-generated by @hey-api/openapi-ts

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type LeadCreateInfo = {
    name: string;
    email: string;
    company: string;
};

export type LeadInfo = {
    id: number;
    name: string;
    email: string;
    company: string;
    stage: number;
    engaged: boolean;
    last_contacted: string;
};

export type LeadUpdateInfo = {
    stage: number;
    engaged: boolean;
    last_contacted: string;
};

export type ListLeadsResponse = {
    leads: Array<LeadInfo>;
    total_count: number;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListLeadsApiLeadsGetData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        page_size?: number;
        search?: string;
        sort_by?: 'stage';
        sort_order?: 'asc' | 'desc';
        secondary_sort_by?: 'last_contacted';
        secondary_sort_order?: 'asc' | 'desc';
    };
    url: '/api/leads/';
};

export type ListLeadsApiLeadsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListLeadsApiLeadsGetError = ListLeadsApiLeadsGetErrors[keyof ListLeadsApiLeadsGetErrors];

export type ListLeadsApiLeadsGetResponses = {
    /**
     * Successful Response
     */
    200: ListLeadsResponse;
};

export type ListLeadsApiLeadsGetResponse = ListLeadsApiLeadsGetResponses[keyof ListLeadsApiLeadsGetResponses];

export type CreateLeadApiLeadsPostData = {
    body: LeadCreateInfo;
    path?: never;
    query?: never;
    url: '/api/leads/';
};

export type CreateLeadApiLeadsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateLeadApiLeadsPostError = CreateLeadApiLeadsPostErrors[keyof CreateLeadApiLeadsPostErrors];

export type CreateLeadApiLeadsPostResponses = {
    /**
     * Successful Response
     */
    201: number;
};

export type CreateLeadApiLeadsPostResponse = CreateLeadApiLeadsPostResponses[keyof CreateLeadApiLeadsPostResponses];

export type DeleteLeadApiLeadsLeadIdDeleteData = {
    body?: never;
    path: {
        lead_id: number;
    };
    query?: never;
    url: '/api/leads/{lead_id}';
};

export type DeleteLeadApiLeadsLeadIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteLeadApiLeadsLeadIdDeleteError = DeleteLeadApiLeadsLeadIdDeleteErrors[keyof DeleteLeadApiLeadsLeadIdDeleteErrors];

export type DeleteLeadApiLeadsLeadIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteLeadApiLeadsLeadIdDeleteResponse = DeleteLeadApiLeadsLeadIdDeleteResponses[keyof DeleteLeadApiLeadsLeadIdDeleteResponses];

export type UpdateLeadApiLeadsLeadIdPatchData = {
    body: LeadUpdateInfo;
    path: {
        lead_id: number;
    };
    query?: never;
    url: '/api/leads/{lead_id}';
};

export type UpdateLeadApiLeadsLeadIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateLeadApiLeadsLeadIdPatchError = UpdateLeadApiLeadsLeadIdPatchErrors[keyof UpdateLeadApiLeadsLeadIdPatchErrors];

export type UpdateLeadApiLeadsLeadIdPatchResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseURL: `${string}://openapi.json` | (string & {});
};