// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { RootGetData, ListLeadsLeadsGetData, ListLeadsLeadsGetResponse, CreateLeadLeadsPostData, CreateLeadLeadsPostResponse, CreateLeadLeadsPostError, DeleteLeadLeadsLeadIdDeleteData, DeleteLeadLeadsLeadIdDeleteResponse, DeleteLeadLeadsLeadIdDeleteError, UpdateLeadLeadsLeadIdPatchData, UpdateLeadLeadsLeadIdPatchError } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Root
 */
export const rootGet = <ThrowOnError extends boolean = false>(options?: Options<RootGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
        url: '/',
        ...options
    });
};

/**
 * List Leads
 */
export const listLeadsLeadsGet = <ThrowOnError extends boolean = false>(options?: Options<ListLeadsLeadsGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ListLeadsLeadsGetResponse, unknown, ThrowOnError>({
        url: '/leads/',
        ...options
    });
};

/**
 * Create Lead
 */
export const createLeadLeadsPost = <ThrowOnError extends boolean = false>(options: Options<CreateLeadLeadsPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateLeadLeadsPostResponse, CreateLeadLeadsPostError, ThrowOnError>({
        url: '/leads/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Delete Lead
 */
export const deleteLeadLeadsLeadIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteLeadLeadsLeadIdDeleteData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteLeadLeadsLeadIdDeleteResponse, DeleteLeadLeadsLeadIdDeleteError, ThrowOnError>({
        url: '/leads/{lead_id}',
        ...options
    });
};

/**
 * Update Lead
 */
export const updateLeadLeadsLeadIdPatch = <ThrowOnError extends boolean = false>(options: Options<UpdateLeadLeadsLeadIdPatchData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<unknown, UpdateLeadLeadsLeadIdPatchError, ThrowOnError>({
        url: '/leads/{lead_id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};