// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { RootGetData, ListLeadsLeadsListGetData, ListLeadsLeadsListGetResponse, CreateLeadLeadsCreatePostData, CreateLeadLeadsCreatePostResponse, CreateLeadLeadsCreatePostError, UpdateLeadLeadsUpdatePutData, DeleteLeadLeadsDeleteDeleteData } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Root
 */
export const rootGet = <ThrowOnError extends boolean = false>(options?: Options<RootGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
        url: '/',
        ...options
    });
};

/**
 * List Leads
 */
export const listLeadsLeadsListGet = <ThrowOnError extends boolean = false>(options?: Options<ListLeadsLeadsListGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ListLeadsLeadsListGetResponse, unknown, ThrowOnError>({
        url: '/leads/list',
        ...options
    });
};

/**
 * Create Lead
 */
export const createLeadLeadsCreatePost = <ThrowOnError extends boolean = false>(options: Options<CreateLeadLeadsCreatePostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateLeadLeadsCreatePostResponse, CreateLeadLeadsCreatePostError, ThrowOnError>({
        url: '/leads/create',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Update Lead
 */
export const updateLeadLeadsUpdatePut = <ThrowOnError extends boolean = false>(options?: Options<UpdateLeadLeadsUpdatePutData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).put<unknown, unknown, ThrowOnError>({
        url: '/leads/update',
        ...options
    });
};

/**
 * Delete Lead
 */
export const deleteLeadLeadsDeleteDelete = <ThrowOnError extends boolean = false>(options?: Options<DeleteLeadLeadsDeleteDeleteData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).delete<unknown, unknown, ThrowOnError>({
        url: '/leads/delete',
        ...options
    });
};