// This file is auto-generated by @hey-api/openapi-ts

export type CreateLeadRequest = {
    name: string;
    email: string;
    company: string;
};

export type CreateLeadResponse = {
    id: number;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type Lead = {
    id?: number | null;
    name: string;
    email: string;
    company: string;
    stage?: number;
    engaged?: boolean;
    last_contacted?: string;
    created_at?: string;
    updated_at?: string;
};

export type ListLeadsResponse = {
    leads: Array<Lead>;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListLeadsLeadsListGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/leads/list';
};

export type ListLeadsLeadsListGetResponses = {
    /**
     * Successful Response
     */
    200: ListLeadsResponse;
};

export type ListLeadsLeadsListGetResponse = ListLeadsLeadsListGetResponses[keyof ListLeadsLeadsListGetResponses];

export type CreateLeadLeadsCreatePostData = {
    body: CreateLeadRequest;
    path?: never;
    query?: never;
    url: '/leads/create';
};

export type CreateLeadLeadsCreatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateLeadLeadsCreatePostError = CreateLeadLeadsCreatePostErrors[keyof CreateLeadLeadsCreatePostErrors];

export type CreateLeadLeadsCreatePostResponses = {
    /**
     * Successful Response
     */
    200: CreateLeadResponse;
};

export type CreateLeadLeadsCreatePostResponse = CreateLeadLeadsCreatePostResponses[keyof CreateLeadLeadsCreatePostResponses];

export type UpdateLeadLeadsUpdatePutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/leads/update';
};

export type UpdateLeadLeadsUpdatePutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteLeadLeadsDeleteDeleteData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/leads/delete';
};

export type DeleteLeadLeadsDeleteDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};