// This file is auto-generated by @hey-api/openapi-ts

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type LeadCreateInfo = {
    name: string;
    email: string;
    company: string;
};

export type LeadInfo = {
    id: number;
    name: string;
    email: string;
    company: string;
    stage: number;
    engaged: boolean;
    last_contacted: string;
};

export type LeadUpdateInfo = {
    stage: number;
    engaged: boolean;
    last_contacted: string;
};

export type ListLeadsResponse = {
    leads: Array<LeadInfo>;
    total_count: number;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListLeadsLeadsGetData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        page_size?: number;
        search?: string;
        sort_by?: 'stage';
        sort_order?: 'asc' | 'desc';
        secondary_sort_by?: 'last_contacted';
        secondary_sort_order?: 'asc' | 'desc';
    };
    url: '/leads/';
};

export type ListLeadsLeadsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListLeadsLeadsGetError = ListLeadsLeadsGetErrors[keyof ListLeadsLeadsGetErrors];

export type ListLeadsLeadsGetResponses = {
    /**
     * Successful Response
     */
    200: ListLeadsResponse;
};

export type ListLeadsLeadsGetResponse = ListLeadsLeadsGetResponses[keyof ListLeadsLeadsGetResponses];

export type CreateLeadLeadsPostData = {
    body: LeadCreateInfo;
    path?: never;
    query?: never;
    url: '/leads/';
};

export type CreateLeadLeadsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateLeadLeadsPostError = CreateLeadLeadsPostErrors[keyof CreateLeadLeadsPostErrors];

export type CreateLeadLeadsPostResponses = {
    /**
     * Successful Response
     */
    201: number;
};

export type CreateLeadLeadsPostResponse = CreateLeadLeadsPostResponses[keyof CreateLeadLeadsPostResponses];

export type DeleteLeadLeadsLeadIdDeleteData = {
    body?: never;
    path: {
        lead_id: number;
    };
    query?: never;
    url: '/leads/{lead_id}';
};

export type DeleteLeadLeadsLeadIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteLeadLeadsLeadIdDeleteError = DeleteLeadLeadsLeadIdDeleteErrors[keyof DeleteLeadLeadsLeadIdDeleteErrors];

export type DeleteLeadLeadsLeadIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteLeadLeadsLeadIdDeleteResponse = DeleteLeadLeadsLeadIdDeleteResponses[keyof DeleteLeadLeadsLeadIdDeleteResponses];

export type UpdateLeadLeadsLeadIdPatchData = {
    body: LeadUpdateInfo;
    path: {
        lead_id: number;
    };
    query?: never;
    url: '/leads/{lead_id}';
};

export type UpdateLeadLeadsLeadIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateLeadLeadsLeadIdPatchError = UpdateLeadLeadsLeadIdPatchErrors[keyof UpdateLeadLeadsLeadIdPatchErrors];

export type UpdateLeadLeadsLeadIdPatchResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};