name: Run Python Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./leads-backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Init Hermit
        uses: cashapp/activate-hermit@v1

      - name: Start services with Docker Compose
        run: make start-stack

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with pytest
        run: |
          pytest --disable-warnings --maxfail=3

      - name: Stop Docker Compose services
        run: make stop-stack
